# Generated by Django 4.1.7 on 2023-03-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountentry',
            name='creditor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='accountentry',
            name='debtor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
