# Generated by Django 4.1.7 on 2023-03-06 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0002_alter_accountentry_creditor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountentry',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entry_account', to='accountapp.entry'),
        ),
        migrations.AlterField(
            model_name='entrydetails',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entry_details', to='accountapp.entry'),
        ),
    ]
