# Generated by Django 4.1.7 on 2023-03-06 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0003_alter_accountentry_entry_alter_entrydetails_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountentry',
            old_name='note',
            new_name='note_acc_en',
        ),
        migrations.RenameField(
            model_name='entrydetails',
            old_name='note',
            new_name='note_dat_en',
        ),
    ]
