# Generated by Django 4.1.7 on 2023-03-06 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0004_rename_note_accountentry_note_acc_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
