# Generated by Django 4.1.7 on 2023-03-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0005_alter_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrydetails',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
