# Generated by Django 4.1.7 on 2023-03-06 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0006_alter_entrydetails_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrydetails',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
