# Generated by Django 4.1.7 on 2023-04-02 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0007_alter_entrydetails_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='fcenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accountapp.financialcenter'),
        ),
    ]
