# Generated by Django 4.1.7 on 2023-04-02 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0008_entry_fcenter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='arvhive',
            field=models.ImageField(upload_to='item_images'),
        ),
    ]
