# Generated by Django 4.1.7 on 2023-04-02 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0009_alter_entry_arvhive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='arvhive',
            field=models.FileField(blank=True, upload_to='doc'),
        ),
    ]
