# Generated by Django 4.2 on 2023-05-08 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0010_alter_entry_arvhive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='date',
            new_name='dateentry',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='invoice',
            new_name='desentry',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='note',
            new_name='docid',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='statement',
            new_name='noteentry',
        ),
    ]
