# Generated by Django 4.2 on 2023-07-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0012_alter_entry_arvhive_alter_entry_date_add_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='arvhive',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/'),
        ),
    ]
