# Generated by Django 4.2 on 2023-07-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0013_alter_entry_arvhive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='arvhive',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
