# Generated by Django 4.2 on 2023-07-12 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0014_alter_entry_arvhive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountentry',
            name='account',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='accountentry',
            name='creditor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creditor_account', to='accountapp.account'),
        ),
        migrations.AlterField(
            model_name='accountentry',
            name='debtor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debtor_account', to='accountapp.account'),
        ),
    ]
