# Generated by Django 4.1.7 on 2023-03-02 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0002_alter_accountentry_creditor_and_more'),
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='account',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='accountapp.account'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
    ]
