# Generated by Django 4.2.6 on 2023-10-24 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0002_rename_group_account_code_remove_account_ceiling_and_more'),
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='branch_defult',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_defult', to='accountapp.branch'),
        ),
        migrations.AddField(
            model_name='profile',
            name='currency_defult',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency_defult', to='accountapp.currency'),
        ),
    ]
