# Generated by Django 4.1.7 on 2023-03-02 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0002_alter_accountentry_creditor_and_more'),
        ('userapp', '0002_alter_profile_account_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accountapp.account'),
        ),
    ]
