# Generated by Django 4.2 on 2023-07-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0011_rename_date_entry_dateentry_and_more'),
        ('userapp', '0003_alter_profile_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='currency_user',
            field=models.ManyToManyField(to='accountapp.currency'),
        ),
    ]
